<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cars')->insert([
            [
                'car_model_id' => 1,
                'brand_id' => 1,
                'base_price' => 25000.00,
                'warranty' => '3 years',
                'environmental_class' => 'Euro 6',
                'availability' => true,
                'engine_capacity' => 2000,
                'fuel_type' => 'Petrol',
                'power_kw' => 150,
                'transmission' => 'Manual',
                'color' => 'Red',
                'width' => 1800,
                'length' => 4500,
                'weight' => 1500,
                'seats_number' => 5,
                'doors_number' => 4,
                'image' => 'path/to/image.jpg',
                'description' => 'A reliable and efficient car.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_model_id' => 2,
                'brand_id' => 1,
                'base_price' => 18000.00,
                'warranty' => '3 years',
                'environmental_class' => 'Euro 6',
                'availability' => true,
                'engine_capacity' => 1000,
                'fuel_type' => 'Petrol',
                'power_kw' => 72,
                'transmission' => 'Manual',
                'color' => 'Blue',
                'width' => 1500,
                'length' => 3700,
                'weight' => 950,
                'seats_number' => 4,
                'doors_number' => 5,
                'image' => 'path/to/image.jpg',
                'description' => 'Compact city car for everyday use.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_model_id' => 3,
                'brand_id' => 2,
                'base_price'          => 90000.00,
                'warranty'            => '5 years',
                'environmental_class' => 'Zero Emissions',
                'availability'        => true,
                'engine_capacity'     => 0, 
                'fuel_type'           => 'Electric',
                'power_kw'            => 610,
                'transmission'        => 'Automatic',
                'color'               => 'Black',
                'width'               => 1964,
                'length'              => 4978,
                'weight'              => 1961,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image' => 'path/to/image.jpg',
                'description' => 'A luxury electric sedan with high performance.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_model_id'        => 4,
                'brand_id'            => 18,
                'base_price'          => 55000.00,
                'warranty'            => '3 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 5000,
                'fuel_type'           => 'Petrol',
                'power_kw'            => 450,
                'transmission'        => 'Automatic',
                'color'               => 'Yellow',
                'width'               => 1900,
                'length'              => 4780,
                'weight'              => 1700,
                'seats_number'        => 4,
                'doors_number'        => 2,
                'image'               => 'https://preview.redd.it/m7xcj8eoygaa1.png?auto=webp&s=94f2570b7278a28e0514df8b15160e36ce7af9f6',
                'description'         => 'A sporty and iconic coupe with raw power.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_model_id' => 5,
                'brand_id' => 13,
                'base_price'          => 23000.00,
                'warranty'            => '3 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 1500,
                'fuel_type'           => 'Petrol',
                'power_kw'            => 130,
                'transmission'        => 'Manual',
                'color'               => 'White',
                'width'               => 1799,
                'length'              => 4677,
                'weight'              => 1400,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'path/to/image.jpg',
                'description'         => 'A compact sedan known for its reliability.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_model_id' => 6,
                'brand_id' => 1,
                'base_price'          => 24000.00,
                'warranty'            => '3 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 1800,
                'fuel_type'           => 'Petrol',
                'power_kw'            => 140,
                'transmission'        => 'Automatic',
                'color'               => 'Silver',
                'width'               => 1780,
                'length'              => 4630,
                'weight'              => 1400,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'path/to/image.jpg',
                'description'         => 'A balanced sedan perfect for families.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_model_id'        => 7,
                'brand_id'            => 21,
                'base_price'          => 42000.00,
                'warranty'            => '3 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 2000,
                'fuel_type'           => 'Diesel',
                'power_kw'            => 140,
                'transmission'        => 'Automatic',
                'color'               => 'Grey',
                'width'               => 1842,
                'length'              => 4762,
                'weight'              => 1550,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'path/to/image.jpg',
                'description'         => 'A premium sedan with modern features.',
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'car_model_id'        => 8,
                'brand_id'            => 22,
                'base_price'          => 45000.00,
                'warranty'            => '4 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 2000,
                'fuel_type'           => 'Diesel',
                'power_kw'            => 190,
                'transmission'        => 'Automatic',
                'color'               => 'Blue',
                'width'               => 1827,
                'length'              => 4709,
                'weight'              => 1555,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'https://www.bmw.co.th/content/dam/bmw/marketTH/bmw_co_th/All%20Models/3series/sedan-long-wheelbase-2023/1001_1680x756px.jpg',
                'description'         => 'A sophisticated sedan that combines luxury, performance, and technology.',
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'car_model_id'        => 9,
                'brand_id'            => 13,
                'base_price'          => 28000.00,
                'warranty'            => '3 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 1500,
                'fuel_type'           => 'Petrol',
                'power_kw'            => 143,
                'transmission'        => 'Automatic',
                'color'               => 'Black',
                'width'               => 1862,
                'length'              => 4901,
                'weight'              => 1500,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'path/to/image.jpg',
                'description'         => 'A midsize sedan offering a blend of comfort, style, and advanced features.',
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'car_model_id'        => 10,
                'brand_id'            => 2,
                'base_price'          => 40000.00,
                'warranty'            => '4 years',
                'environmental_class' => 'Zero Emissions',
                'availability'        => true,
                'engine_capacity'     => 0,
                'fuel_type'           => 'Electric',
                'power_kw'            => 283,
                'transmission'        => 'Automatic',
                'color'               => 'White',
                'width'               => 1850,
                'length'              => 4694,
                'weight'              => 1750,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'https://www.shop4tesla.com/cdn/shop/articles/tesla-model-3-uber-230000-km-und-tausende-euro-gespart-956682.jpg?v=1728598029',
                'description'         => 'A cutting-edge electric sedan offering impressive performance, range, and technology.',
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
            [
                'car_model_id'        => 11,
                'brand_id'            => 25,
                'base_price'          => 37000.00,
                'warranty'            => '3 years',
                'environmental_class' => 'Euro 6',
                'availability'        => true,
                'engine_capacity'     => 6200,
                'fuel_type'           => 'Petrol',
                'power_kw'            => 527,
                'transmission'        => 'Automatic',
                'color'               => 'Red',
                'width'               => 1981,
                'length'              => 5100,
                'weight'              => 2000,
                'seats_number'        => 5,
                'doors_number'        => 4,
                'image'               => 'https://www.cavauto.com/wp-content/webp-express/webp-images/uploads/2022/08/dodge-charger-2021-srt-hellcat.jpeg.webp',
                'description'         => 'A powerful and iconic muscle car with high performance and bold styling.',
                'created_at'          => now(),
                'updated_at'          => now(),
            ],
        ]);
    }
}